/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdvancedForm: typeof import('./components/SearchForm/advancedForm/index.vue')['default']
    AvatarCropper: typeof import('./components/AvatarCropper/index.vue')['default']
    CodeMirror: typeof import('./components/CodeMirror/index.vue')['default']
    CountTo: typeof import('./components/CountTo/index.vue')['default']
    EditableProTable: typeof import('./components/Table/EditableProTable/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Gauge: typeof import('./components/Charts/gauge/index.vue')['default']
    Keyboard: typeof import('./components/Charts/Keyboard.vue')['default']
    LineMarker: typeof import('./components/Charts/LineMarker.vue')['default']
    MixChart: typeof import('./components/Charts/MixChart.vue')['default']
    Multiline: typeof import('./components/DataScreen/Multiline/index.vue')['default']
    Pie: typeof import('./components/DataScreen/pie/index.vue')['default']
    Pipeline: typeof import('./components/pipeline/index.vue')['default']
    PropTable: typeof import('./components/Table/PropTable/index.vue')['default']
    RightClickMenu: typeof import('./components/RightClickMenu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    SwitchDark: typeof import('./components/SwitchDark/index.vue')['default']
    Upload: typeof import('./components/Upload/index.vue')['default']
    WangEdior: typeof import('./components/WangEdior/index.vue')['default']
    ZbPipelineStart: typeof import('./components/pipeline/zb-pipeline-start.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
